// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Uint32 Function()>()
external int cs_abi_version();

@ffi.Native<ffi.Int32 Function(ffi.Int32, ffi.Int32)>()
external int cs_smoke_add(int a, int b);
